spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shiro?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 222333

# mybatis-plus打印SQL日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

shiro:
  enabled: true       # 开启 shiro，默认为 true
  web:
    enabled: true     # 开启 shiro Web，默认为 true
  loginUrl: /login    # 登录地址，默认为"login.jsp"
  successUrl: /index  # 登录成功后跳转的地址，默认为"/"
  unauthorizedUrl: /unauthorized    # 未获授权默认跳转地址
  sessionManager:
    sessionIdCookieEnabled: true       # 是否允许通过 Cookie 实现会话跟踪，默认为 true。
    sessionIdUrlRewritingEnabled: true # 是否允许通过 URL 参数实现会话跟踪，默认为 true。若网站支持 Cookie，可关闭此选项。


