### 搜索医院网点
GET http://localhost:16001/staff/branch
Accept: */*
Cache-Control: no-cache
Authorization: Base eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ7XG4gIFwiY3VycmVudFVzZXJVbmlxdWVNYXJrXCIgOiBcIjg3NmExZjgwZTZlNDQ5ZDU4NWUyNWYxNzYxYTJjZGNjXCIsXG4gIFwidXNlclR5cGVcIiA6IFwiMTFcIixcbiAgXCJ1c2VySWRcIiA6IFwiMVwiXG59IiwicnQiOiJleUowZVhBaU9pSktWMVFpTENKaGJHY2lPaUpJVXpJMU5pSjkuZXlKcWRHa2lPaUk0TnpaaE1XWTRNR1UyWlRRME9XUTFPRFZsTWpWbU1UYzJNV0V5WTJSall5SXNJbWxoZENJNk1UWXhPVEEzTWpNMk5pd2ljM1ZpSWpvaWUxeHVJQ0JjSW1OMWNuSmxiblJWYzJWeVZXNXBjWFZsVFdGeWExd2lJRG9nWENJNE56WmhNV1k0TUdVMlpUUTBPV1ExT0RWbE1qVm1NVGMyTVdFeVkyUmpZMXdpTEZ4dUlDQmNJblZ6WlhKVWVYQmxYQ0lnT2lCY0lqRXhYQ0lzWEc0Z0lGd2lkWE5sY2tsa1hDSWdPaUJjSWpGY0lseHVmU0lzSW1WNGNDSTZNVFl4T1RZM056RTJObjAudFBjLWNRcTFDQUllWnlkSUUxMjVpVkZfYXFFVF83VUxTX18zdnVpZzBPZyIsImV4cCI6MTY1MDYwODM2NiwiaWF0IjoxNjE5MDcyMzY2LCJqdGkiOiI4NzZhMWY4MGU2ZTQ0OWQ1ODVlMjVmMTc2MWEyY2RjYyJ9.ETdcAAKtYgD_4xvY4OvqHJw-qJ_QRD9Fyzn1NscTTjE
###

### 岗位添加权限
POST http://localhost:16001/staff/power
Content-Type: application/json
Authorization: Base eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ7XG4gIFwiY3VycmVudFVzZXJVbmlxdWVNYXJrXCIgOiBcIjg3NmExZjgwZTZlNDQ5ZDU4NWUyNWYxNzYxYTJjZGNjXCIsXG4gIFwidXNlclR5cGVcIiA6IFwiMTFcIixcbiAgXCJ1c2VySWRcIiA6IFwiMVwiXG59IiwicnQiOiJleUowZVhBaU9pSktWMVFpTENKaGJHY2lPaUpJVXpJMU5pSjkuZXlKcWRHa2lPaUk0TnpaaE1XWTRNR1UyWlRRME9XUTFPRFZsTWpWbU1UYzJNV0V5WTJSall5SXNJbWxoZENJNk1UWXhPVEEzTWpNMk5pd2ljM1ZpSWpvaWUxeHVJQ0JjSW1OMWNuSmxiblJWYzJWeVZXNXBjWFZsVFdGeWExd2lJRG9nWENJNE56WmhNV1k0TUdVMlpUUTBPV1ExT0RWbE1qVm1NVGMyTVdFeVkyUmpZMXdpTEZ4dUlDQmNJblZ6WlhKVWVYQmxYQ0lnT2lCY0lqRXhYQ0lzWEc0Z0lGd2lkWE5sY2tsa1hDSWdPaUJjSWpGY0lseHVmU0lzSW1WNGNDSTZNVFl4T1RZM056RTJObjAudFBjLWNRcTFDQUllWnlkSUUxMjVpVkZfYXFFVF83VUxTX18zdnVpZzBPZyIsImV4cCI6MTY1MDYwODM2NiwiaWF0IjoxNjE5MDcyMzY2LCJqdGkiOiI4NzZhMWY4MGU2ZTQ0OWQ1ODVlMjVmMTc2MWEyY2RjYyJ9.ETdcAAKtYgD_4xvY4OvqHJw-qJ_QRD9Fyzn1NscTTjE

{

	"postJobId": "1353946485172191234",
	"postJobName": "Java开发",
	"channelNo": "1385471475930546177",
	"branchList": [{
		"id": "1381926916772073473",
		"name": "浙江中医医院2",
		"branchList": [{
			"id": "1386953769157156866",
			"name": "1222"
		}, {
			"id": "1386954304606199809",
			"name": "12"
		}]
	}]
}
###

### 根据岗位ID查询网点列表
GET http://localhost:16001/staff/1353946485172191234/branch
Accept: */*
Cache-Control: no-cache
Authorization: Base eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ7XG4gIFwiY3VycmVudFVzZXJVbmlxdWVNYXJrXCIgOiBcIjg3NmExZjgwZTZlNDQ5ZDU4NWUyNWYxNzYxYTJjZGNjXCIsXG4gIFwidXNlclR5cGVcIiA6IFwiMTFcIixcbiAgXCJ1c2VySWRcIiA6IFwiMVwiXG59IiwicnQiOiJleUowZVhBaU9pSktWMVFpTENKaGJHY2lPaUpJVXpJMU5pSjkuZXlKcWRHa2lPaUk0TnpaaE1XWTRNR1UyWlRRME9XUTFPRFZsTWpWbU1UYzJNV0V5WTJSall5SXNJbWxoZENJNk1UWXhPVEEzTWpNMk5pd2ljM1ZpSWpvaWUxeHVJQ0JjSW1OMWNuSmxiblJWYzJWeVZXNXBjWFZsVFdGeWExd2lJRG9nWENJNE56WmhNV1k0TUdVMlpUUTBPV1ExT0RWbE1qVm1NVGMyTVdFeVkyUmpZMXdpTEZ4dUlDQmNJblZ6WlhKVWVYQmxYQ0lnT2lCY0lqRXhYQ0lzWEc0Z0lGd2lkWE5sY2tsa1hDSWdPaUJjSWpGY0lseHVmU0lzSW1WNGNDSTZNVFl4T1RZM056RTJObjAudFBjLWNRcTFDQUllWnlkSUUxMjVpVkZfYXFFVF83VUxTX18zdnVpZzBPZyIsImV4cCI6MTY1MDYwODM2NiwiaWF0IjoxNjE5MDcyMzY2LCJqdGkiOiI4NzZhMWY4MGU2ZTQ0OWQ1ODVlMjVmMTc2MWEyY2RjYyJ9.ETdcAAKtYgD_4xvY4OvqHJw-qJ_QRD9Fyzn1NscTTjE
###

### 根据指定岗位指定网点权限
GET http://localhost:16001/staff/1353946485172191234/power?hospitalId=1380412316289359874&branchId=1380421188307771394
Accept: */*
Cache-Control: no-cache
Authorization: Base eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ7XG4gIFwiY3VycmVudFVzZXJVbmlxdWVNYXJrXCIgOiBcIjg3NmExZjgwZTZlNDQ5ZDU4NWUyNWYxNzYxYTJjZGNjXCIsXG4gIFwidXNlclR5cGVcIiA6IFwiMTFcIixcbiAgXCJ1c2VySWRcIiA6IFwiMVwiXG59IiwicnQiOiJleUowZVhBaU9pSktWMVFpTENKaGJHY2lPaUpJVXpJMU5pSjkuZXlKcWRHa2lPaUk0TnpaaE1XWTRNR1UyWlRRME9XUTFPRFZsTWpWbU1UYzJNV0V5WTJSall5SXNJbWxoZENJNk1UWXhPVEEzTWpNMk5pd2ljM1ZpSWpvaWUxeHVJQ0JjSW1OMWNuSmxiblJWYzJWeVZXNXBjWFZsVFdGeWExd2lJRG9nWENJNE56WmhNV1k0TUdVMlpUUTBPV1ExT0RWbE1qVm1NVGMyTVdFeVkyUmpZMXdpTEZ4dUlDQmNJblZ6WlhKVWVYQmxYQ0lnT2lCY0lqRXhYQ0lzWEc0Z0lGd2lkWE5sY2tsa1hDSWdPaUJjSWpGY0lseHVmU0lzSW1WNGNDSTZNVFl4T1RZM056RTJObjAudFBjLWNRcTFDQUllWnlkSUUxMjVpVkZfYXFFVF83VUxTX18zdnVpZzBPZyIsImV4cCI6MTY1MDYwODM2NiwiaWF0IjoxNjE5MDcyMzY2LCJqdGkiOiI4NzZhMWY4MGU2ZTQ0OWQ1ODVlMjVmMTc2MWEyY2RjYyJ9.ETdcAAKtYgD_4xvY4OvqHJw-qJ_QRD9Fyzn1NscTTjE
###

### 编辑岗位网点权限
PUT http://localhost:16001/staff/power
Content-Type: application/json
Authorization: Base eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ7XG4gIFwiY3VycmVudFVzZXJVbmlxdWVNYXJrXCIgOiBcIjg3NmExZjgwZTZlNDQ5ZDU4NWUyNWYxNzYxYTJjZGNjXCIsXG4gIFwidXNlclR5cGVcIiA6IFwiMTFcIixcbiAgXCJ1c2VySWRcIiA6IFwiMVwiXG59IiwicnQiOiJleUowZVhBaU9pSktWMVFpTENKaGJHY2lPaUpJVXpJMU5pSjkuZXlKcWRHa2lPaUk0TnpaaE1XWTRNR1UyWlRRME9XUTFPRFZsTWpWbU1UYzJNV0V5WTJSall5SXNJbWxoZENJNk1UWXhPVEEzTWpNMk5pd2ljM1ZpSWpvaWUxeHVJQ0JjSW1OMWNuSmxiblJWYzJWeVZXNXBjWFZsVFdGeWExd2lJRG9nWENJNE56WmhNV1k0TUdVMlpUUTBPV1ExT0RWbE1qVm1NVGMyTVdFeVkyUmpZMXdpTEZ4dUlDQmNJblZ6WlhKVWVYQmxYQ0lnT2lCY0lqRXhYQ0lzWEc0Z0lGd2lkWE5sY2tsa1hDSWdPaUJjSWpGY0lseHVmU0lzSW1WNGNDSTZNVFl4T1RZM056RTJObjAudFBjLWNRcTFDQUllWnlkSUUxMjVpVkZfYXFFVF83VUxTX18zdnVpZzBPZyIsImV4cCI6MTY1MDYwODM2NiwiaWF0IjoxNjE5MDcyMzY2LCJqdGkiOiI4NzZhMWY4MGU2ZTQ0OWQ1ODVlMjVmMTc2MWEyY2RjYyJ9.ETdcAAKtYgD_4xvY4OvqHJw-qJ_QRD9Fyzn1NscTTjE

{
	"postJobId": 1353946485172191234,
	"hospitalId": 1380412316289359874,
    "branchId": 1380421188307771394,
	"openOrder": true,
	"openInvoice": false,
	"openStock": true,
	"openData": false,
	"openGroup": true,
	"openMessage": false
}
###
