### 用户登录
POST http://localhost:16001/user/login
Content-Type: application/json

{
  "email": "ops_test@seechangetech.com",
  "password": "12345678"
}

### 版本列表
GET http://{{host}}/page-center/version
channelNo: CN48596

### 版本操作历史
GET http://{{host}}/page-center/version/1334077845131456514
channelNo: CN48596

### 操作日志
GET http://localhost:16002/page-center/operation-log
channelNo: CN48596
clientType: 1

### 版本发布
POST http://{{host}}/page-center/release
channelNo: CN48596

### 移动端页面列表
GET http://localhost:16001/mobile/page/list
channelNo: CN31941

### 页面列表
GET http://localhost:16001/page-manager?queryType=0&versionId=1377141360734445569
channelNo: CN31941
Authorization: Base eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ7XG4gIFwiY3VycmVudFVzZXJVbmlxdWVNYXJrXCIgOiBcImY2OGI3NDA1OWVhZTQ5MDg4ZjU1ZWNmMWNmOWMyNTQ5XCIsXG4gIFwidXNlclR5cGVcIiA6IFwiMTFcIixcbiAgXCJ1c2VySWRcIiA6IFwiMVwiXG59IiwicnQiOiJleUowZVhBaU9pSktWMVFpTENKaGJHY2lPaUpJVXpJMU5pSjkuZXlKcWRHa2lPaUptTmpoaU56UXdOVGxsWVdVME9UQTRPR1kxTldWalpqRmpaamxqTWpVME9TSXNJbWxoZENJNk1UWXhPVE16TWpjMU1Td2ljM1ZpSWpvaWUxeHVJQ0JjSW1OMWNuSmxiblJWYzJWeVZXNXBjWFZsVFdGeWExd2lJRG9nWENKbU5qaGlOelF3TlRsbFlXVTBPVEE0T0dZMU5XVmpaakZqWmpsak1qVTBPVndpTEZ4dUlDQmNJblZ6WlhKVWVYQmxYQ0lnT2lCY0lqRXhYQ0lzWEc0Z0lGd2lkWE5sY2tsa1hDSWdPaUJjSWpGY0lseHVmU0lzSW1WNGNDSTZNVFl4T1Rrek56VTFNWDAucFRZd3FEU3BnTlVlRGdsekZkSXNsSkpPemhLQ1pBV0FhZHZYN2h2aG1CRSIsImV4cCI6MTY1MDg2ODc1MSwiaWF0IjoxNjE5MzMyNzUxLCJqdGkiOiJmNjhiNzQwNTllYWU0OTA4OGY1NWVjZjFjZjljMjU0OSJ9.6Klg3H1x8YEiEhDHyBBQwzIWwumX5a7nID9vsvvTRKk

### 新增页面
POST http://localhost:16001/page-manager
Content-Type: application/json
channelNo: CN48596

{
  "pageName": "首页",
  "pageType": 0,
  "businessType": 0,
  "folderId": null,
  "isFolder": false
}

### 编辑页面
PUT http://localhost:16001/page-manager/pOaHkPpso%
Content-Type: application/json
channelNo: CN48596

{
  "lastId": 1328968314688888834
}

### 页面详情
GET http://localhost:16001/page-manager/1BtFUboWfoB?versionId=
clientType: 1
envType: 0
channelNo: CN74916
Authorization: Base eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ7XG4gIFwiY3VycmVudFVzZXJVbmlxdWVNYXJrXCIgOiBcIjhiYjg0ZDkxZGJiNTQwNzc5NDg0YTg5ZmNmYTczYWZmXCIsXG4gIFwidXNlclR5cGVcIiA6IFwiMTBcIixcbiAgXCJ1c2VySWRcIiA6IFwiMVwiXG59IiwicnQiOiJleUowZVhBaU9pSktWMVFpTENKaGJHY2lPaUpJVXpJMU5pSjkuZXlKcWRHa2lPaUkwTnpBeU56UmtPVEJoTXpZMFl6SXpZalkxTXpGaU9EWmxNREJpTkRrMllTSXNJbWxoZENJNk1UWXdOelV3TXpJd09Td2ljM1ZpSWpvaWUxeHVJQ0JjSW1OMWNuSmxiblJWYzJWeVZXNXBjWFZsVFdGeWExd2lJRG9nWENJNFltSTROR1E1TVdSaVlqVTBNRGMzT1RRNE5HRTRPV1pqWm1FM00yRm1abHdpTEZ4dUlDQmNJblZ6WlhKVWVYQmxYQ0lnT2lCY0lqRXdYQ0lzWEc0Z0lGd2lkWE5sY2tsa1hDSWdPaUJjSWpGY0lseHVmU0lzSW1WNGNDSTZNVFl3T0RFd09EQXdPWDAucFpTM3lKVzhTbGVLbnNLUVFkZXRJMUU5T0ItdUsya0hQMGEzRjY1UWxVSSIsImV4cCI6MTYzOTAzOTIwOCwiaWF0IjoxNjA3NTAzMjA4LCJqdGkiOiI0NzAyNzRkOTBhMzY0YzIzYjY1MzFiODZlMDBiNDk2YSJ9.Fo9TTjjxyTAriit70-R-0WNxZiffBFtsOvwHum2-bl4

### 新增组件
POST http://localhost:16001/page-manager/1334422502285717505/module
Content-Type: application/json

{
  "pageIds": 0,
  "moduleType": 4,
  "webJson": "{\"blockId\":\"1273a797-ce18-4fc8-b792-dcc54b9c30e6\",\"belongType\":0,\"category\":0,\"moduleType\":4,\"name\":\"divider\",\"status\":\"PREVIEW\",\"layoutType\":1,\"style\":{\"height\":10}}"
}

### 编辑/拖拽组件
PUT http://localhost:16001/page-manager/1328968314688888834/component/1328968314688888834
Content-Type: application/json

{
  "componentType": 0,
  "webJson": "[{\"name\":\"按钮名\",\"sort\":0,\"linkModuleId\":0,\"webJson\":\"color=red\"}]"
}

### 预览
POST http://localhost:16001/page-manager/preview
channelNo: CN48596
Authorization: Base eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ7XG4gIFwiY3VycmVudFVzZXJVbmlxdWVNYXJrXCIgOiBcIjhiYjg0ZDkxZGJiNTQwNzc5NDg0YTg5ZmNmYTczYWZmXCIsXG4gIFwidXNlclR5cGVcIiA6IFwiMTBcIixcbiAgXCJ1c2VySWRcIiA6IFwiMVwiXG59IiwicnQiOiJleUowZVhBaU9pSktWMVFpTENKaGJHY2lPaUpJVXpJMU5pSjkuZXlKcWRHa2lPaUkwTnpBeU56UmtPVEJoTXpZMFl6SXpZalkxTXpGaU9EWmxNREJpTkRrMllTSXNJbWxoZENJNk1UWXdOelV3TXpJd09Td2ljM1ZpSWpvaWUxeHVJQ0JjSW1OMWNuSmxiblJWYzJWeVZXNXBjWFZsVFdGeWExd2lJRG9nWENJNFltSTROR1E1TVdSaVlqVTBNRGMzT1RRNE5HRTRPV1pqWm1FM00yRm1abHdpTEZ4dUlDQmNJblZ6WlhKVWVYQmxYQ0lnT2lCY0lqRXdYQ0lzWEc0Z0lGd2lkWE5sY2tsa1hDSWdPaUJjSWpGY0lseHVmU0lzSW1WNGNDSTZNVFl3T0RFd09EQXdPWDAucFpTM3lKVzhTbGVLbnNLUVFkZXRJMUU5T0ItdUsya0hQMGEzRjY1UWxVSSIsImV4cCI6MTYzOTAzOTIwOCwiaWF0IjoxNjA3NTAzMjA4LCJqdGkiOiI0NzAyNzRkOTBhMzY0YzIzYjY1MzFiODZlMDBiNDk2YSJ9.Fo9TTjjxyTAriit70-R-0WNxZiffBFtsOvwHum2-bl4

### 导出
GET https://insurance-api.touchealth.com/user/export?startDate=&endDate=&userId=&mobileNo=&realName=&inviteMobileNo=&inviteCode=&pageNo=3&pageSize=5000
Authorization: Base eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ7XG4gIFwicGxhdGZvcm1LZXlcIiA6IFwidG91Y2hlYWx0aC5pbnN1cmFuY2VcIixcbiAgXCJwbGF0Zm9ybUlkXCIgOiBcIjEzXCIsXG4gIFwidXNlcklkXCIgOiBcIjQ3MDU2OVwiXG59IiwicnQiOiJleUowZVhBaU9pSktWMVFpTENKaGJHY2lPaUpJVXpJMU5pSjkuZXlKcWRHa2lPaUpsWWpNd01UZ3lPR1ZpTURnMFl6aGlPRFkyTjJNd01XTmxNek5oWWprNVppSXNJbWxoZENJNk1UWXdPREU1TVRnNE15d2ljM1ZpSWpvaWUxeHVJQ0JjSW5Cc1lYUm1iM0p0UzJWNVhDSWdPaUJjSW5SdmRXTm9aV0ZzZEdndWFXNXpkWEpoYm1ObFhDSXNYRzRnSUZ3aWNHeGhkR1p2Y20xSlpGd2lJRG9nWENJeE0xd2lMRnh1SUNCY0luVnpaWEpKWkZ3aUlEb2dYQ0kwTnpBMU5qbGNJbHh1ZlNJc0ltVjRjQ0k2TVRZd09EYzVOalk0TTMwLmphenFkQXlIVlJlLVIwNmZkRWU5OXJhUWpmaFpSMnotRFR4d2t3WnlSTWsiLCJleHAiOjE2MDg3OTY2ODMsImlhdCI6MTYwODE5MTg4MywianRpIjoiZWIzMDE4MjhlYjA4NGM4Yjg2NjdjMDFjZTMzYWI5OWYifQ.nZRhkBLmALtiRqJrpZ3tqw3c6dsZI9txGmJKTFiRk2I

### 发布历史
GET http://localhost:16001/page-center/version/history
Authorization: Base eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ7XG4gIFwiY3VycmVudFVzZXJVbmlxdWVNYXJrXCIgOiBcIjA0YzBlYzc2MmQxOTRjMmM4YWUxYTcxMTA1OGVlNGU0XCIsXG4gIFwidXNlclR5cGVcIiA6IFwiMTFcIixcbiAgXCJ1c2VySWRcIiA6IFwiMVwiXG59IiwicnQiOiJleUowZVhBaU9pSktWMVFpTENKaGJHY2lPaUpJVXpJMU5pSjkuZXlKcWRHa2lPaUl3TkdNd1pXTTNOakprTVRrMFl6SmpPR0ZsTVdFM01URXdOVGhsWlRSbE5DSXNJbWxoZENJNk1UWXlOVFkwTURBNU5pd2ljM1ZpSWpvaWUxeHVJQ0JjSW1OMWNuSmxiblJWYzJWeVZXNXBjWFZsVFdGeWExd2lJRG9nWENJd05HTXdaV00zTmpKa01UazBZekpqT0dGbE1XRTNNVEV3TlRobFpUUmxORndpTEZ4dUlDQmNJblZ6WlhKVWVYQmxYQ0lnT2lCY0lqRXhYQ0lzWEc0Z0lGd2lkWE5sY2tsa1hDSWdPaUJjSWpGY0lseHVmU0lzSW1WNGNDSTZNVFl5TmpJME5EZzVObjAuZnozZ2FGSy0wcWM2SzF4OWpjQjdwVzlQLTQ5VXlfWUpyM2V5QjRuZlpoVSIsImV4cCI6MTY1NzE3NjA5NiwiaWF0IjoxNjI1NjQwMDk2LCJqdGkiOiIwNGMwZWM3NjJkMTk0YzJjOGFlMWE3MTEwNThlZTRlNCJ9.8cxZnyqYZKAX-ApQAsaEBl8MnKgbPad-fiiq4hCFfEY
channelNo: CN31941

###
