### 用户中心列表
GET http://localhost:16001/user-center?channelId=1&pageNo=1&pageSize=10
channelNo: CN31941
Authorization: Base eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ7XG4gIFwiY3VycmVudFVzZXJVbmlxdWVNYXJrXCIgOiBcImNkMWQyODIzZjA3MjQ0M2Y5Zjg4NTRlYmIyNzZlNjc2XCIsXG4gIFwidXNlclR5cGVcIiA6IFwiMTFcIixcbiAgXCJ1c2VySWRcIiA6IFwiMVwiXG59IiwicnQiOiJleUowZVhBaU9pSktWMVFpTENKaGJHY2lPaUpJVXpJMU5pSjkuZXlKcWRHa2lPaUpqWkRGa01qZ3lNMll3TnpJME5ETm1PV1k0T0RVMFpXSmlNamMyWlRZM05pSXNJbWxoZENJNk1UWXlNRGc0TlRRd01pd2ljM1ZpSWpvaWUxeHVJQ0JjSW1OMWNuSmxiblJWYzJWeVZXNXBjWFZsVFdGeWExd2lJRG9nWENKalpERmtNamd5TTJZd056STBORE5tT1dZNE9EVTBaV0ppTWpjMlpUWTNObHdpTEZ4dUlDQmNJblZ6WlhKVWVYQmxYQ0lnT2lCY0lqRXhYQ0lzWEc0Z0lGd2lkWE5sY2tsa1hDSWdPaUJjSWpGY0lseHVmU0lzSW1WNGNDSTZNVFl5TVRRNU1ESXdNbjAuT1FadjEzVVM1WXRYejV0eTZZVEtpZDN5eVhENHpGVzVFV0NGaHJfaU5tNCIsImV4cCI6MTY1MjQyMTQwMiwiaWF0IjoxNjIwODg1NDAyLCJqdGkiOiJjZDFkMjgyM2YwNzI0NDNmOWY4ODU0ZWJiMjc2ZTY3NiJ9.c36G-QZ4XRF-qr_z2V_4RL6yS0zbAwk1nrkL-07822U

###
