# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data},

POST http://{{host}}/perms/staff/auth
Content-Type: application/json
channelNo: CN00001
Authorization: {{auth}}

{
  "staffId": 1352545386977329153,
  "postJobIds": ["1352544371747139585"],
  "permList": [
    {
      "id": "1349895790968029185"
    }
  ]
}

### 添加用户权限

POST http://{{host}}/perms/template/auth
Content-Type: application/json
channelNo: CN00001
Authorization: {{auth}}

{
  "postJobId": 1352544338989625345,
  "permList": [
    {
      "id": 1349895790863171586
    },
    {
      "id": 1349895790942863362
    }
  ]
}

### 添加岗位模板权限

GET http://{{host}}/perms/template/all?channelNo=CN00001&search=
Content-Type: application/json
channelNo: CN0001
Authorization: {{auth}}

{}

### 查询所有部门岗位权限模板

GET http://{{host}}/perms/menu?channelNo=CN00001
Accept: application/json
channelNo: CN00001
Authorization: {{auth}}

{}

### 查询岗位或员工的权限菜单

GET http://{{host}}/perms/1349895790942863362/detail?channelNo=CN00001&postJobId=
Content-Type: application/json
channelNo: CN00001
Authorization: {{auth}}

{}

### 查询菜单明细

GET http://{{host}}/perms/all?postJobId=1352544371747139585
Content-Type: application/json
channelNo: CN00001
Authorization: {{auth}}

{}

### 查询菜单和其下的所有权限