# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST http://{{host}}/pic/add
Content-Type: multipart/form-data; boundary=WebAppBoundary
channelNo: CN00001
Authorization: Base eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ7XG4gIFwiY3VycmVudFVzZXJVbmlxdWVNYXJrXCIgOiBcImM5MjY3NGUyN2I0MDQ0ZTNhYjNkMjdmMWJiMDZkZjhkXCIsXG4gIFwidXNlclR5cGVcIiA6IFwiMTBcIixcbiAgXCJ1c2VySWRcIiA6IFwiMVwiXG59IiwicnQiOiJleUowZVhBaU9pSktWMVFpTENKaGJHY2lPaUpJVXpJMU5pSjkuZXlKcWRHa2lPaUkzWlRreVltSXhOVGxrWW1FME5UWmpPV1V3TWpNM05UVTJNREExTjJZeFppSXNJbWxoZENJNk1UWXdPVGc1TlRjek9Td2ljM1ZpSWpvaWUxeHVJQ0JjSW1OMWNuSmxiblJWYzJWeVZXNXBjWFZsVFdGeWExd2lJRG9nWENKak9USTJOelJsTWpkaU5EQTBOR1V6WVdJelpESTNaakZpWWpBMlpHWTRaRndpTEZ4dUlDQmNJblZ6WlhKVWVYQmxYQ0lnT2lCY0lqRXdYQ0lzWEc0Z0lGd2lkWE5sY2tsa1hDSWdPaUJjSWpGY0lseHVmU0lzSW1WNGNDSTZNVFl4TURVd01EVXpPWDAuazBGMEVaNHFZb2EzQ3ZYeHJEWXB4WUhfenlVWUg1aHVPZWNwNUNodlV4WSIsImV4cCI6MTY0MTQzMTczOSwiaWF0IjoxNjA5ODk1NzM5LCJqdGkiOiI3ZTkyYmIxNTlkYmE0NTZjOWUwMjM3NTU2MDA1N2YxZiJ9.JsAp_bk9ntT1OVYbS7i-OLJClzKqcx4A3VedtQOEyh0

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="恐鳌之心.jpg"

< C:\Users\P\Pictures\恐鳌之心.jpg
--WebAppBoundary--
Content-Disposition: form-data; name="name"

恐鳌之心.jpg
--WebAppBoundary--
Content-Disposition: form-data; name="folderId"

1330073682326953985
--WebAppBoundary--

### 添加图片

POST http://{{host}}/pic/batchAdd
Content-Type: multipart/form-data; boundary=WebAppBoundary
channelNo: 10001

--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="Aghanim神杖.png"

< C:\Users\P\Pictures\Aghanim神杖.png
--WebAppBoundary--
Content-Disposition: form-data; name="names"

Aghanim神杖.png
--WebAppBoundary--
Content-Disposition: form-data; name="files"; filename="王者之戒.png"

< C:\Users\P\Pictures\王者之戒.png
--WebAppBoundary--
Content-Disposition: form-data; name="names"

王者之戒.png
--WebAppBoundary--
Content-Disposition: form-data; name="folderId"

1330073682326953985
--WebAppBoundary--

### 批量添加图片


POST http://{{host}}/pic/addfolder
Content-Type: application/json
channelNo: 10001

{
  "folderId": 1330073682326953985,
  "name": "TI"
}

### 添加图片文件夹

GET http://{{host}}/pic/list?folderId=-1&pageNo=1&pageSize=16
Content-Type: application/json
channelNo: CN16985
Authorization: Base eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ7XG4gIFwiY3VycmVudFVzZXJVbmlxdWVNYXJrXCIgOiBcImM5NjZmNTM1OTk0MjQ4NDc5ZWNmZGQxMTkwNzhkOGVjXCIsXG4gIFwidXNlclR5cGVcIiA6IFwiMTBcIixcbiAgXCJ1c2VySWRcIiA6IFwiMVwiXG59IiwicnQiOiJleUowZVhBaU9pSktWMVFpTENKaGJHY2lPaUpJVXpJMU5pSjkuZXlKcWRHa2lPaUpqTkRnd05EUXhaVEJtTnpZME5EVmpPVEk0TUdVMllqZ3dPRFpqT0RVeFpDSXNJbWxoZENJNk1UWXhNRE0wTlRBeU5Td2ljM1ZpSWpvaWUxeHVJQ0JjSW1OMWNuSmxiblJWYzJWeVZXNXBjWFZsVFdGeWExd2lJRG9nWENKak9UWTJaalV6TlRrNU5ESTBPRFEzT1dWalptUmtNVEU1TURjNFpEaGxZMXdpTEZ4dUlDQmNJblZ6WlhKVWVYQmxYQ0lnT2lCY0lqRXdYQ0lzWEc0Z0lGd2lkWE5sY2tsa1hDSWdPaUJjSWpGY0lseHVmU0lzSW1WNGNDSTZNVFl4TURrME9UZ3lOWDAuRDZjcGlKNXdTWFhOMWpQNUxsc3ZpQ0p1c0hIdFdXTGpxN3VyX1hiN052MCIsImV4cCI6MTY0MTg4MTAyNSwiaWF0IjoxNjEwMzQ1MDI1LCJqdGkiOiJjNDgwNDQxZTBmNzY0NDVjOTI4MGU2YjgwODZjODUxZCJ9.9oWre-kASe5YVhepr1zULjf_y2hCXn72sePHLi8yUqc

{}

### 查询图片资源列表

PUT http://{{host}}/pic/move
Content-Type: application/json
channelNo: 10001

{
  "id": 1330072782271258625,
  "folderId": 1330077111308853250
}

### 将图片或图片文件夹放到某个文件夹下

PUT http://{{host}}/pic/rename
Content-Type: application/json
channelNo: 10001

{
  "id": 1330072782271258625,
  "name": "黑皇杖.png"
}

### 修改图片或图片文件夹名

DELETE http://{{host}}/pic/delete/1330072782271258625
Content-Type: application/json
channelNo: 10001

{}

### 删除图片或图片文件夹

POST http://{{host}}/pic/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary
channelNo: CN00001
Authorization: Base eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ7XG4gIFwiY3VycmVudFVzZXJVbmlxdWVNYXJrXCIgOiBcImM5MjY3NGUyN2I0MDQ0ZTNhYjNkMjdmMWJiMDZkZjhkXCIsXG4gIFwidXNlclR5cGVcIiA6IFwiMTBcIixcbiAgXCJ1c2VySWRcIiA6IFwiMVwiXG59IiwicnQiOiJleUowZVhBaU9pSktWMVFpTENKaGJHY2lPaUpJVXpJMU5pSjkuZXlKcWRHa2lPaUkzWlRreVltSXhOVGxrWW1FME5UWmpPV1V3TWpNM05UVTJNREExTjJZeFppSXNJbWxoZENJNk1UWXdPVGc1TlRjek9Td2ljM1ZpSWpvaWUxeHVJQ0JjSW1OMWNuSmxiblJWYzJWeVZXNXBjWFZsVFdGeWExd2lJRG9nWENKak9USTJOelJsTWpkaU5EQTBOR1V6WVdJelpESTNaakZpWWpBMlpHWTRaRndpTEZ4dUlDQmNJblZ6WlhKVWVYQmxYQ0lnT2lCY0lqRXdYQ0lzWEc0Z0lGd2lkWE5sY2tsa1hDSWdPaUJjSWpGY0lseHVmU0lzSW1WNGNDSTZNVFl4TURVd01EVXpPWDAuazBGMEVaNHFZb2EzQ3ZYeHJEWXB4WUhfenlVWUg1aHVPZWNwNUNodlV4WSIsImV4cCI6MTY0MTQzMTczOSwiaWF0IjoxNjA5ODk1NzM5LCJqdGkiOiI3ZTkyYmIxNTlkYmE0NTZjOWUwMjM3NTU2MDA1N2YxZiJ9.JsAp_bk9ntT1OVYbS7i-OLJClzKqcx4A3VedtQOEyh0

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="恐鳌之心.jpg"

< C:\Users\P\Pictures\恐鳌之心.jpg
--WebAppBoundary--
Content-Disposition: form-data; name="filename"

恐鳌之心.jpg
--WebAppBoundary--

### 上传图片