# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST http://{{host}}/user/login
Content-Type: application/json

{
  "loginType": 1,
  "mobile": "18000000003",
  "verificationCode": "198237"
}

### 短信验证码登录

POST http://{{host}}/user/login
Content-Type: application/json

{
  "email": "sckj@admintouchealth.com",
  "password": "12345678"
}

### 账号密码登录

POST http://{{host}}/user/login
Content-Type: multipart/form-data; boundary=WebAppBoundary
channelNo: 10001

--WebAppBoundary--
Content-Disposition: form-data; name="email"

ops_test@seechangetech.com
--WebAppBoundary--
Content-Disposition: form-data; name="password"

12345678
--WebAppBoundary--

### 登录

POST http://{{host}}/staff/import
Content-Type: multipart/form-data; boundary=WebAppBoundary
channelNo: CN00001
Authorization: {{auth}}

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="员工导入2.xlsx"

< C:\Users\P\Downloads\员工导入2.xlsx
--WebAppBoundary--
Content-Disposition: form-data; name="verifyCode"

198237
--WebAppBoundary--

### 导入员工

POST http://{{host}}/staff/add
Content-Type: application/json
channelNo: CN00001
Authorization: {{auth}}

{
  "realName": "Gemu",
  "code": "0041",
  "mobileNo": "18311111110",
  "email": "gm@touchealth.com",
  "password": "123456",
  "password1": "123456",
  "deptId": 1352540774162575361,
  "postJobId": 1352544371747139585,
  "staffStatus": 0
}

### 添加员工

PUT http://{{host}}/staff/edit
Content-Type: application/json
channelNo: CN59964
Authorization: {{auth}}

{
  "id": 1352221505667321858,
  "realName": "Gemu",
  "code": "0041",
  "mobileNo": "18311111110",
  "email": "gm@touchealth.com",
  "password": "123456",
  "password1": "123456",
  "deptId": 1352219764414504962,
  "postJobId": 1352221038577045505,
  "staffStatus": 0
}

### 编辑员工

DELETE http://{{host}}/staff/delete/1346353708630368257
Content-Type: application/json
channelNo: CN59964
Authorization: {{auth}}

{}

### 删除员工

GET http://{{host}}/staff/page?search=287
Content-Type: application/json
channelNo: CN59964
Authorization: {{auth}}

{}

### 分页查询员工列表

GET http://{{host}}/staff/templates/1?channelNo=CN59964
Content-Type: application/json
channelNo: CN59964
Authorization: {{auth}}

{}

### 查询用户模板

GET http://{{host}}/staff/1
Content-Type: application/json
channelNo: CN59964
Authorization: {{auth}}

{}

### 查询用户

POST http://{{host}}/staff/bindchannel
Content-Type: application/json
channelNo: CN0001
Authorization: {{auth}}

{
  "staffId": 2,
  "channelNos": ["CN54339","CN0001"]
}

### 为用户绑定渠道