spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 222333
#    url: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shiro?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

mybatis:
  mapper-locations: classpath:com/how2java/mapper/*.xml
  type-aliases-package: com.how2java.pojo

server:
  context-path: /shiro
